{"name": "test01_add_member[电话重复，断言失败]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 60104 == 0", "trace": "self = <test_case.member.test_member.TestMember object at 0x00000157FCBC2D90>, userid = 'tong6', name = 'tong6'\nmobile = '13222661165', errcode = 0, errmsg = 'created'\n\n    @pytest.mark.parametrize((\"userid,name,mobile,errcode,errmsg\"),add_data,ids=add_ids)\n    def test01_add_member(self,userid,name,mobile,errcode,errmsg):\n        log.info(\"-------开始测试增加成员-------\")\n    \n        res=self.member.add_member(self.token,userid,name,mobile)\n        log.info(f\"打印响应结果:{res}\" )\n        log.info(\"-------测试结束-------\")\n>       assert res[\"errcode\"] == errcode\nE       assert 60104 == 0\n\ntest_member.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "01af8d9f-6a23-4eeb-aec2-c20896fb63fc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cb2e7d1d-1e10-40ab-88aa-33c77ea59bde-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "userid", "value": "'tong6'"}, {"name": "name", "value": "'tong6'"}, {"name": "mobile", "value": "'13222661165'"}, {"name": "errcode", "value": "0"}, {"name": "errmsg", "value": "'created'"}], "start": 1603977984568, "stop": 1603977985134, "uuid": "313bc480-4e97-4118-8c26-3614d9b87795", "historyId": "46ac891b6c8ed7c7fafd74fc2aea3aad", "testCaseId": "a244cf98b03e2f32dd1c74ce8e22d393", "fullName": "test_case.member.test_member.TestMember#test01_add_member", "labels": [{"name": "parentSuite", "value": "test_case.member"}, {"name": "suite", "value": "test_member"}, {"name": "subSuite", "value": "TestMember"}, {"name": "host", "value": "LAPTOP-4F3KR3S3"}, {"name": "thread", "value": "3600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.member.test_member"}]}